security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    # 1) Endpoint de login -> renvoie un JWT
    login:
      pattern: ^/api/auth/login
      stateless: true
      json_login:
        check_path: /api/auth/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # 2) Tout le reste de l'API -> protégé par JWT
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    # Public
    - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/listings, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/listings/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/recipes, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/recipes/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/forum, roles: PUBLIC_ACCESS, methods: [GET] }

    # Admin
    - { path: ^/api/admin, roles: ROLE_ADMIN }
  
   # User (tout le reste API)
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

